version: '3.8'

services:
  app:
    build:
      context: ..  # Build from root directory
      dockerfile: .devcontainer/Dockerfile  # Explicit Dockerfile path
    volumes:
      - ..:/workspace:cached
      - ./.devcontainer:/container-config:cached  # Add this line
    command: sleep infinity
    network_mode: service:db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  sqlvolume:
